### PR TITLE
added CRUD

### PR DESCRIPTION
**Pull request by shrutijodevops**
added CRUD

### CODE REVIEW

**Comment by ayukha-zepto** [comment]
Ran Plan for 2 projects:

1. dir: `Account-Zepto-qa/zepto_delete` workspace: `default`
1. dir: `Account-Zepto-qa/zepto_patching` workspace: `default`

### 1. dir: `Account-Zepto-qa/zepto_delete` workspace: `default`
<details><summary>Show Output</summary>

```diff
Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
+ create

Terraform will perform the following actions:

  # aws_instance.zepto-delete-qa will be created
+ resource "aws_instance" "zepto-delete-qa" {
      + ami                                  = "ami-0ad8ef5571e16cef7"
      + arn                                  = (known after apply)
      + associate_public_ip_address          = (known after apply)
      + availability_zone                    = (known after apply)
      + cpu_core_count                       = (known after apply)
      + cpu_threads_per_core                 = (known after apply)
      + disable_api_stop                     = (known after apply)
      + disable_api_termination              = (known after apply)
      + ebs_optimized                        = (known after apply)
      + get_password_data                    = false
      + host_id                              = (known after apply)
      + host_resource_group_arn              = (known after apply)
      + iam_instance_profile                 = (known after apply)
      + id                                   = (known after apply)
      + instance_initiated_shutdown_behavior = (known after apply)
      + instance_lifecycle                   = (known after apply)
      + instance_state                       = (known after apply)
      + instance_type                        = "t3.micro"
      + ipv6_address_count                   = (known after apply)
      + ipv6_addresses                       = (known after apply)
      + key_name                             = (known after apply)
      + monitoring                           = (known after apply)
      + outpost_arn                          = (known after apply)
      + password_data                        = (known after apply)
      + placement_group                      = (known after apply)
      + placement_partition_number           = (known after apply)
      + primary_network_interface_id         = (known after apply)
      + private_dns                          = (known after apply)
      + private_ip                           = (known after apply)
      + public_dns                           = (known after apply)
      + public_ip                            = (known after apply)
      + secondary_private_ips                = (known after apply)
      + security_groups                      = (known after apply)
      + source_dest_check                    = true
      + spot_instance_request_id             = (known after apply)
      + subnet_id                            = (known after apply)
      + tags                                 = {
          + "Name" = "zepto-delete-qa"
        }
      + tags_all                             = {
          + "Name" = "zepto-delete-qa"
        }
      + tenancy                              = (known after apply)
      + user_data                            = (known after apply)
      + user_data_base64                     = (known after apply)
      + user_data_replace_on_change          = false
      + vpc_security_group_ids               = (known after apply)
    }

Plan: 1 to add, 0 to change, 0 to destroy.
```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d Account-Zepto-qa/zepto_delete`
* :put_litter_in_its_place: To **delete** this plan click [here](http:/lock?id=ayukha-zepto%252FAtlantis_Test%252FAccount-Zepto-qa%252Fzepto_delete%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -d Account-Zepto-qa/zepto_delete`
</details>
Plan: 1 to add, 0 to change, 0 to destroy.

---
### 2. dir: `Account-Zepto-qa/zepto_patching` workspace: `default`
<details><summary>Show Output</summary>

```diff
Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
+ create

Terraform will perform the following actions:

  # aws_instance.zepto_patching_qa will be created
+ resource "aws_instance" "zepto_patching_qa" {
      + ami                                  = "ami-0ad8ef5571e16cef7"
      + arn                                  = (known after apply)
      + associate_public_ip_address          = (known after apply)
      + availability_zone                    = (known after apply)
      + cpu_core_count                       = (known after apply)
      + cpu_threads_per_core                 = (known after apply)
      + disable_api_stop                     = (known after apply)
      + disable_api_termination              = (known after apply)
      + ebs_optimized                        = (known after apply)
      + get_password_data                    = false
      + host_id                              = (known after apply)
      + host_resource_group_arn              = (known after apply)
      + iam_instance_profile                 = (known after apply)
      + id                                   = (known after apply)
      + instance_initiated_shutdown_behavior = (known after apply)
      + instance_lifecycle                   = (known after apply)
      + instance_state                       = (known after apply)
      + instance_type                        = "t3.micro"
      + ipv6_address_count                   = (known after apply)
      + ipv6_addresses                       = (known after apply)
      + key_name                             = (known after apply)
      + monitoring                           = (known after apply)
      + outpost_arn                          = (known after apply)
      + password_data                        = (known after apply)
      + placement_group                      = (known after apply)
      + placement_partition_number           = (known after apply)
      + primary_network_interface_id         = (known after apply)
      + private_dns                          = (known after apply)
      + private_ip                           = (known after apply)
      + public_dns                           = (known after apply)
      + public_ip                            = (known after apply)
      + secondary_private_ips                = (known after apply)
      + security_groups                      = (known after apply)
      + source_dest_check                    = true
      + spot_instance_request_id             = (known after apply)
      + subnet_id                            = (known after apply)
      + tags                                 = {
          + "Name" = "zepto-patching-qa"
        }
      + tags_all                             = {
          + "Name" = "zepto-patching-qa"
        }
      + tenancy                              = (known after apply)
      + user_data                            = (known after apply)
      + user_data_base64                     = (known after apply)
      + user_data_replace_on_change          = false
      + vpc_security_group_ids               = (known after apply)
    }

Plan: 1 to add, 0 to change, 0 to destroy.
```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d Account-Zepto-qa/zepto_patching`
* :put_litter_in_its_place: To **delete** this plan click [here](http:/lock?id=ayukha-zepto%252FAtlantis_Test%252FAccount-Zepto-qa%252Fzepto_patching%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -d Account-Zepto-qa/zepto_patching`
</details>
Plan: 1 to add, 0 to change, 0 to destroy.

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by ayukha-zepto** [comment]
Ran Plan for dir: `Account-Zepto-qa/zepto_patching` workspace: `default`

<details><summary>Show Output</summary>

```diff
Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
+ create

Terraform will perform the following actions:

  # aws_instance.zepto_patching_qa will be created
+ resource "aws_instance" "zepto_patching_qa" {
      + ami                                  = "ami-0ad8ef5571e16cef7"
      + arn                                  = (known after apply)
      + associate_public_ip_address          = (known after apply)
      + availability_zone                    = (known after apply)
      + cpu_core_count                       = (known after apply)
      + cpu_threads_per_core                 = (known after apply)
      + disable_api_stop                     = (known after apply)
      + disable_api_termination              = (known after apply)
      + ebs_optimized                        = (known after apply)
      + get_password_data                    = false
      + host_id                              = (known after apply)
      + host_resource_group_arn              = (known after apply)
      + iam_instance_profile                 = (known after apply)
      + id                                   = (known after apply)
      + instance_initiated_shutdown_behavior = (known after apply)
      + instance_lifecycle                   = (known after apply)
      + instance_state                       = (known after apply)
      + instance_type                        = "t3.micro"
      + ipv6_address_count                   = (known after apply)
      + ipv6_addresses                       = (known after apply)
      + key_name                             = (known after apply)
      + monitoring                           = (known after apply)
      + outpost_arn                          = (known after apply)
      + password_data                        = (known after apply)
      + placement_group                      = (known after apply)
      + placement_partition_number           = (known after apply)
      + primary_network_interface_id         = (known after apply)
      + private_dns                          = (known after apply)
      + private_ip                           = (known after apply)
      + public_dns                           = (known after apply)
      + public_ip                            = (known after apply)
      + secondary_private_ips                = (known after apply)
      + security_groups                      = (known after apply)
      + source_dest_check                    = true
      + spot_instance_request_id             = (known after apply)
      + subnet_id                            = (known after apply)
      + tags                                 = {
          + "Name" = "zepto-patching-qa"
        }
      + tags_all                             = {
          + "Name" = "zepto-patching-qa"
        }
      + tenancy                              = (known after apply)
      + user_data                            = (known after apply)
      + user_data_base64                     = (known after apply)
      + user_data_replace_on_change          = false
      + vpc_security_group_ids               = (known after apply)
    }

Plan: 1 to add, 0 to change, 0 to destroy.
```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d Account-Zepto-qa/zepto_patching`
* :put_litter_in_its_place: To **delete** this plan click [here](http:/lock?id=ayukha-zepto%252FAtlantis_Test%252FAccount-Zepto-qa%252Fzepto_patching%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -d Account-Zepto-qa/zepto_patching`
</details>
Plan: 1 to add, 0 to change, 0 to destroy.

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by shrutijodevops** [comment]
atlantis apply

**Comment by shrutijodevops** [comment]
atlantis plan -- -destroy

**Comment by ayukha-zepto** [comment]
Ran Plan for 0 projects:

**Comment by ayukha-zepto** [comment]
Ran Plan for dir: `Account-Zepto-qa/zepto_patching` workspace: `default`

```diff
aws_instance.zepto_patching_qa: Refreshing state... [id=i-0b44c3eafe228dc92]

No changes. Your infrastructure matches the configuration.

Terraform has compared your real infrastructure against your configuration
and found no differences, so no changes are needed.
```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d Account-Zepto-qa/zepto_patching`
* :put_litter_in_its_place: To **delete** this plan click [here](http:/lock?id=ayukha-zepto%252FAtlantis_Test%252FAccount-Zepto-qa%252Fzepto_patching%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -d Account-Zepto-qa/zepto_patching`

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by shrutijodevops** [comment]
atlantis plan -- -destroy

**Comment by ayukha-zepto** [comment]
Ran Plan for dir: `Account-Zepto-qa/zepto_patching` workspace: `default`

<details><summary>Show Output</summary>

```diff
aws_instance.zepto_patching_qa: Refreshing state... [id=i-0b44c3eafe228dc92]

Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
- destroy

Terraform will perform the following actions:

  # aws_instance.zepto_patching_qa will be destroyed
- resource "aws_instance" "zepto_patching_qa" {
      - ami                                  = "ami-0ad8ef5571e16cef7" -> null
      - arn                                  = "arn:aws:ec2:ap-south-1:149309639702:instance/i-0b44c3eafe228dc92" -> null
      - associate_public_ip_address          = true -> null
      - availability_zone                    = "ap-south-1b" -> null
      - cpu_core_count                       = 1 -> null
      - cpu_threads_per_core                 = 2 -> null
      - disable_api_stop                     = false -> null
      - disable_api_termination              = false -> null
      - ebs_optimized                        = false -> null
      - get_password_data                    = false -> null
      - hibernation                          = false -> null
      - id                                   = "i-0b44c3eafe228dc92" -> null
      - instance_initiated_shutdown_behavior = "stop" -> null
      - instance_state                       = "running" -> null
      - instance_type                        = "t3.micro" -> null
      - ipv6_address_count                   = 0 -> null
      - ipv6_addresses                       = [] -> null
      - monitoring                           = false -> null
      - placement_partition_number           = 0 -> null
      - primary_network_interface_id         = "eni-003084072bde7c4f3" -> null
      - private_dns                          = "ip-172-31-8-176.ap-south-1.compute.internal" -> null
      - private_ip                           = "172.31.8.176" -> null
      - public_dns                           = "ec2-3-109-211-78.ap-south-1.compute.amazonaws.com" -> null
      - public_ip                            = "3.109.211.78" -> null
      - secondary_private_ips                = [] -> null
      - security_groups                      = [
          - "default",
        ] -> null
      - source_dest_check                    = true -> null
      - subnet_id                            = "subnet-04f0cbb41104c7eab" -> null
      - tags                                 = {
          - "Name" = "zepto-patching-qa"
        } -> null
      - tags_all                             = {
          - "Name" = "zepto-patching-qa"
        } -> null
      - tenancy                              = "default" -> null
      - user_data_replace_on_change          = false -> null
      - vpc_security_group_ids               = [
          - "sg-054fd80d29103298e",
        ] -> null

      - capacity_reservation_specification {
          - capacity_reservation_preference = "open" -> null
        }

      - cpu_options {
          - core_count       = 1 -> null
          - threads_per_core = 2 -> null
        }

      - credit_specification {
          - cpu_credits = "unlimited" -> null
        }

      - enclave_options {
          - enabled = false -> null
        }

      - maintenance_options {
          - auto_recovery = "default" -> null
        }

      - metadata_options {
          - http_endpoint               = "enabled" -> null
          - http_put_response_hop_limit = 1 -> null
          - http_tokens                 = "optional" -> null
          - instance_metadata_tags      = "disabled" -> null
        }

      - private_dns_name_options {
          - enable_resource_name_dns_a_record    = false -> null
          - enable_resource_name_dns_aaaa_record = false -> null
          - hostname_type                        = "ip-name" -> null
        }

      - root_block_device {
          - delete_on_termination = true -> null
          - device_name           = "/dev/xvda" -> null
          - encrypted             = false -> null
          - iops                  = 100 -> null
          - tags                  = {} -> null
          - throughput            = 0 -> null
          - volume_id             = "vol-0b436d2346056812a" -> null
          - volume_size           = 8 -> null
          - volume_type           = "gp2" -> null
        }
    }

Plan: 0 to add, 0 to change, 1 to destroy.
```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d Account-Zepto-qa/zepto_patching`
* :put_litter_in_its_place: To **delete** this plan click [here](http:/lock?id=ayukha-zepto%252FAtlantis_Test%252FAccount-Zepto-qa%252Fzepto_patching%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -d Account-Zepto-qa/zepto_patching -- -destroy`
</details>
Plan: 0 to add, 0 to change, 1 to destroy.

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by shrutijodevops** [comment]
atlantis apply -d Account-Zepto-qa/zepto_patching

**Comment by ayukha-zepto** [comment]
Ran Apply for dir: `Account-Zepto-qa/zepto_patching` workspace: `default`

```diff
aws_instance.zepto_patching_qa: Destroying... [id=i-0b44c3eafe228dc92]
aws_instance.zepto_patching_qa: Still destroying... [id=i-0b44c3eafe228dc92, 10s elapsed]
aws_instance.zepto_patching_qa: Still destroying... [id=i-0b44c3eafe228dc92, 20s elapsed]
aws_instance.zepto_patching_qa: Still destroying... [id=i-0b44c3eafe228dc92, 30s elapsed]
aws_instance.zepto_patching_qa: Still destroying... [id=i-0b44c3eafe228dc92, 40s elapsed]
aws_instance.zepto_patching_qa: Destruction complete after 50s

Apply complete! Resources: 0 added, 0 changed, 1 destroyed.
```

**Comment by ayukha-zepto** [comment]
Locks and plans deleted for the projects and workspaces modified in this pull request:

- dir: `Account-Zepto-qa/zepto_patching` workspace: `default`

**Pull request closed without merging**
