### PR TITLE
Test 2

### PR DESCRIPTION
**Pull request by ayukha-zepto**

### CODE REVIEW

**Comment by ayukha-zepto** [comment]
Ran Plan for 4 projects:

1. dir: `Account-Zepto-production/zepto_rewards` workspace: `default`
1. dir: `Account-Zepto-production/zepto_wallet` workspace: `default`
1. dir: `Account-Zepto-qa/qa/zepto_rewards` workspace: `default`
1. dir: `Account-Zepto-qa/qa/zepto_wallet` workspace: `default`

### 1. dir: `Account-Zepto-production/zepto_rewards` workspace: `default`
<details><summary>Show Output</summary>

```diff
aws_instance.zepto_rewards: Refreshing state... [id=i-0c443956a11601c58]

Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
+ create
- destroy

Terraform will perform the following actions:

  # aws_instance.zepto_rewards will be destroyed
  # (because aws_instance.zepto_rewards is not in configuration)
- resource "aws_instance" "zepto_rewards" {
      - ami                                  = "ami-0ad8ef5571e16cef7" -> null
      - arn                                  = "arn:aws:ec2:ap-south-1:149309639702:instance/i-0c443956a11601c58" -> null
      - associate_public_ip_address          = true -> null
      - availability_zone                    = "ap-south-1c" -> null
      - cpu_core_count                       = 1 -> null
      - cpu_threads_per_core                 = 2 -> null
      - disable_api_stop                     = false -> null
      - disable_api_termination              = false -> null
      - ebs_optimized                        = false -> null
      - get_password_data                    = false -> null
      - hibernation                          = false -> null
      - id                                   = "i-0c443956a11601c58" -> null
      - instance_initiated_shutdown_behavior = "stop" -> null
      - instance_state                       = "running" -> null
      - instance_type                        = "t3.micro" -> null
      - ipv6_address_count                   = 0 -> null
      - ipv6_addresses                       = [] -> null
      - monitoring                           = false -> null
      - placement_partition_number           = 0 -> null
      - primary_network_interface_id         = "eni-0b5e5804ee695a5e9" -> null
      - private_dns                          = "ip-172-31-25-140.ap-south-1.compute.internal" -> null
      - private_ip                           = "172.31.25.140" -> null
      - public_dns                           = "ec2-65-0-60-233.ap-south-1.compute.amazonaws.com" -> null
      - public_ip                            = "65.0.60.233" -> null
      - secondary_private_ips                = [] -> null
      - security_groups                      = [
          - "default",
        ] -> null
      - source_dest_check                    = true -> null
      - subnet_id                            = "subnet-0c4c19f094dcd30ea" -> null
      - tags                                 = {
          - "Name" = "Zepto-rewards"
        } -> null
      - tags_all                             = {
          - "Name" = "Zepto-rewards"
        } -> null
      - tenancy                              = "default" -> null
      - user_data_replace_on_change          = false -> null
      - vpc_security_group_ids               = [
          - "sg-054fd80d29103298e",
        ] -> null

      - capacity_reservation_specification {
          - capacity_reservation_preference = "open" -> null
        }

      - cpu_options {
          - core_count       = 1 -> null
          - threads_per_core = 2 -> null
        }

      - credit_specification {
          - cpu_credits = "unlimited" -> null
        }

      - enclave_options {
          - enabled = false -> null
        }

      - maintenance_options {
          - auto_recovery = "default" -> null
        }

      - metadata_options {
          - http_endpoint               = "enabled" -> null
          - http_put_response_hop_limit = 1 -> null
          - http_tokens                 = "optional" -> null
          - instance_metadata_tags      = "disabled" -> null
        }

      - private_dns_name_options {
          - enable_resource_name_dns_a_record    = false -> null
          - enable_resource_name_dns_aaaa_record = false -> null
          - hostname_type                        = "ip-name" -> null
        }

      - root_block_device {
          - delete_on_termination = true -> null
          - device_name           = "/dev/xvda" -> null
          - encrypted             = false -> null
          - iops                  = 100 -> null
          - tags                  = {} -> null
          - throughput            = 0 -> null
          - volume_id             = "vol-0fe4572fde605cf13" -> null
          - volume_size           = 8 -> null
          - volume_type           = "gp2" -> null
        }
    }

  # aws_instance.zepto_rewards_prod will be created
+ resource "aws_instance" "zepto_rewards_prod" {
      + ami                                  = "ami-0ad8ef5571e16cef7"
      + arn                                  = (known after apply)
      + associate_public_ip_address          = (known after apply)
      + availability_zone                    = (known after apply)
      + cpu_core_count                       = (known after apply)
      + cpu_threads_per_core                 = (known after apply)
      + disable_api_stop                     = (known after apply)
      + disable_api_termination              = (known after apply)
      + ebs_optimized                        = (known after apply)
      + get_password_data                    = false
      + host_id                              = (known after apply)
      + host_resource_group_arn              = (known after apply)
      + iam_instance_profile                 = (known after apply)
      + id                                   = (known after apply)
      + instance_initiated_shutdown_behavior = (known after apply)
      + instance_lifecycle                   = (known after apply)
      + instance_state                       = (known after apply)
      + instance_type                        = "t3.micro"
      + ipv6_address_count                   = (known after apply)
      + ipv6_addresses                       = (known after apply)
      + key_name                             = (known after apply)
      + monitoring                           = (known after apply)
      + outpost_arn                          = (known after apply)
      + password_data                        = (known after apply)
      + placement_group                      = (known after apply)
      + placement_partition_number           = (known after apply)
      + primary_network_interface_id         = (known after apply)
      + private_dns                          = (known after apply)
      + private_ip                           = (known after apply)
      + public_dns                           = (known after apply)
      + public_ip                            = (known after apply)
      + secondary_private_ips                = (known after apply)
      + security_groups                      = (known after apply)
      + source_dest_check                    = true
      + spot_instance_request_id             = (known after apply)
      + subnet_id                            = (known after apply)
      + tags                                 = {
          + "Name" = "Zepto-rewards-prod"
        }
      + tags_all                             = {
          + "Name" = "Zepto-rewards-prod"
        }
      + tenancy                              = (known after apply)
      + user_data                            = (known after apply)
      + user_data_base64                     = (known after apply)
      + user_data_replace_on_change          = false
      + vpc_security_group_ids               = (known after apply)
    }

Plan: 1 to add, 0 to change, 1 to destroy.
```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d Account-Zepto-production/zepto_rewards`
* :put_litter_in_its_place: To **delete** this plan click [here](http:/lock?id=ayukha-zepto%252FAtlantis_Test%252FAccount-Zepto-production%252Fzepto_rewards%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -d Account-Zepto-production/zepto_rewards`
</details>
Plan: 1 to add, 0 to change, 1 to destroy.

---
### 2. dir: `Account-Zepto-production/zepto_wallet` workspace: `default`
<details><summary>Show Output</summary>

```diff
aws_instance.Zepto_wallet: Refreshing state... [id=i-0504eb4a77cdb8db7]

Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
+ create
- destroy

Terraform will perform the following actions:

  # aws_instance.Zepto_wallet will be destroyed
  # (because aws_instance.Zepto_wallet is not in configuration)
- resource "aws_instance" "Zepto_wallet" {
      - ami                                  = "ami-0ad8ef5571e16cef7" -> null
      - arn                                  = "arn:aws:ec2:ap-south-1:149309639702:instance/i-0504eb4a77cdb8db7" -> null
      - associate_public_ip_address          = true -> null
      - availability_zone                    = "ap-south-1c" -> null
      - cpu_core_count                       = 1 -> null
      - cpu_threads_per_core                 = 2 -> null
      - disable_api_stop                     = false -> null
      - disable_api_termination              = false -> null
      - ebs_optimized                        = false -> null
      - get_password_data                    = false -> null
      - hibernation                          = false -> null
      - id                                   = "i-0504eb4a77cdb8db7" -> null
      - instance_initiated_shutdown_behavior = "stop" -> null
      - instance_state                       = "running" -> null
      - instance_type                        = "t3.micro" -> null
      - ipv6_address_count                   = 0 -> null
      - ipv6_addresses                       = [] -> null
      - monitoring                           = false -> null
      - placement_partition_number           = 0 -> null
      - primary_network_interface_id         = "eni-0f1c652239f3d4980" -> null
      - private_dns                          = "ip-172-31-20-239.ap-south-1.compute.internal" -> null
      - private_ip                           = "172.31.20.239" -> null
      - public_dns                           = "ec2-65-1-127-81.ap-south-1.compute.amazonaws.com" -> null
      - public_ip                            = "65.1.127.81" -> null
      - secondary_private_ips                = [] -> null
      - security_groups                      = [
          - "default",
        ] -> null
      - source_dest_check                    = true -> null
      - subnet_id                            = "subnet-0c4c19f094dcd30ea" -> null
      - tags                                 = {
          - "Name" = "Zepto_wallet"
        } -> null
      - tags_all                             = {
          - "Name" = "Zepto_wallet"
        } -> null
      - tenancy                              = "default" -> null
      - user_data_replace_on_change          = false -> null
      - vpc_security_group_ids               = [
          - "sg-054fd80d29103298e",
        ] -> null

      - capacity_reservation_specification {
          - capacity_reservation_preference = "open" -> null
        }

      - cpu_options {
          - core_count       = 1 -> null
          - threads_per_core = 2 -> null
        }

      - credit_specification {
          - cpu_credits = "unlimited" -> null
        }

      - enclave_options {
          - enabled = false -> null
        }

      - maintenance_options {
          - auto_recovery = "default" -> null
        }

      - metadata_options {
          - http_endpoint               = "enabled" -> null
          - http_put_response_hop_limit = 1 -> null
          - http_tokens                 = "optional" -> null
          - instance_metadata_tags      = "disabled" -> null
        }

      - private_dns_name_options {
          - enable_resource_name_dns_a_record    = false -> null
          - enable_resource_name_dns_aaaa_record = false -> null
          - hostname_type                        = "ip-name" -> null
        }

      - root_block_device {
          - delete_on_termination = true -> null
          - device_name           = "/dev/xvda" -> null
          - encrypted             = false -> null
          - iops                  = 100 -> null
          - tags                  = {} -> null
          - throughput            = 0 -> null
          - volume_id             = "vol-0500a53fb751d32e1" -> null
          - volume_size           = 8 -> null
          - volume_type           = "gp2" -> null
        }
    }

  # aws_instance.Zepto_wallet_prod will be created
+ resource "aws_instance" "Zepto_wallet_prod" {
      + ami                                  = "ami-0ad8ef5571e16cef7"
      + arn                                  = (known after apply)
      + associate_public_ip_address          = (known after apply)
      + availability_zone                    = (known after apply)
      + cpu_core_count                       = (known after apply)
      + cpu_threads_per_core                 = (known after apply)
      + disable_api_stop                     = (known after apply)
      + disable_api_termination              = (known after apply)
      + ebs_optimized                        = (known after apply)
      + get_password_data                    = false
      + host_id                              = (known after apply)
      + host_resource_group_arn              = (known after apply)
      + iam_instance_profile                 = (known after apply)
      + id                                   = (known after apply)
      + instance_initiated_shutdown_behavior = (known after apply)
      + instance_lifecycle                   = (known after apply)
      + instance_state                       = (known after apply)
      + instance_type                        = "t3.micro"
      + ipv6_address_count                   = (known after apply)
      + ipv6_addresses                       = (known after apply)
      + key_name                             = (known after apply)
      + monitoring                           = (known after apply)
      + outpost_arn                          = (known after apply)
      + password_data                        = (known after apply)
      + placement_group                      = (known after apply)
      + placement_partition_number           = (known after apply)
      + primary_network_interface_id         = (known after apply)
      + private_dns                          = (known after apply)
      + private_ip                           = (known after apply)
      + public_dns                           = (known after apply)
      + public_ip                            = (known after apply)
      + secondary_private_ips                = (known after apply)
      + security_groups                      = (known after apply)
      + source_dest_check                    = true
      + spot_instance_request_id             = (known after apply)
      + subnet_id                            = (known after apply)
      + tags                                 = {
          + "Name" = "Zepto_wallet_prod"
        }
      + tags_all                             = {
          + "Name" = "Zepto_wallet_prod"
        }
      + tenancy                              = (known after apply)
      + user_data                            = (known after apply)
      + user_data_base64                     = (known after apply)
      + user_data_replace_on_change          = false
      + vpc_security_group_ids               = (known after apply)
    }

Plan: 1 to add, 0 to change, 1 to destroy.
```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d Account-Zepto-production/zepto_wallet`
* :put_litter_in_its_place: To **delete** this plan click [here](http:/lock?id=ayukha-zepto%252FAtlantis_Test%252FAccount-Zepto-production%252Fzepto_wallet%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -d Account-Zepto-production/zepto_wallet`
</details>
Plan: 1 to add, 0 to change, 1 to destroy.

---
### 3. dir: `Account-Zepto-qa/qa/zepto_rewards` workspace: `default`
<details><summary>Show Output</summary>

```diff
aws_instance.zepto_rewards: Refreshing state... [id=i-0c443956a11601c58]

Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
~ update in-place

Terraform will perform the following actions:

  # aws_instance.zepto_rewards will be updated in-place
~ resource "aws_instance" "zepto_rewards" {
        id                                   = "i-0c443956a11601c58"
      ~ tags                                 = {
          ~ "Name" = "Zepto-rewards" -> "Zepto-rewards-test2"
        }
      ~ tags_all                             = {
          ~ "Name" = "Zepto-rewards" -> "Zepto-rewards-test2"
        }
        # (30 unchanged attributes hidden)

        # (8 unchanged blocks hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d Account-Zepto-qa/qa/zepto_rewards`
* :put_litter_in_its_place: To **delete** this plan click [here](http:/lock?id=ayukha-zepto%252FAtlantis_Test%252FAccount-Zepto-qa%252Fqa%252Fzepto_rewards%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -d Account-Zepto-qa/qa/zepto_rewards`
</details>
Plan: 0 to add, 1 to change, 0 to destroy.

---
### 4. dir: `Account-Zepto-qa/qa/zepto_wallet` workspace: `default`
<details><summary>Show Output</summary>

```diff
aws_instance.Zepto_wallet: Refreshing state... [id=i-0504eb4a77cdb8db7]

Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
~ update in-place

Terraform will perform the following actions:

  # aws_instance.Zepto_wallet will be updated in-place
~ resource "aws_instance" "Zepto_wallet" {
        id                                   = "i-0504eb4a77cdb8db7"
      ~ tags                                 = {
          ~ "Name" = "Zepto_wallet" -> "Zepto_wallet_test"
        }
      ~ tags_all                             = {
          ~ "Name" = "Zepto_wallet" -> "Zepto_wallet_test"
        }
        # (30 unchanged attributes hidden)

        # (8 unchanged blocks hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d Account-Zepto-qa/qa/zepto_wallet`
* :put_litter_in_its_place: To **delete** this plan click [here](http:/lock?id=ayukha-zepto%252FAtlantis_Test%252FAccount-Zepto-qa%252Fqa%252Fzepto_wallet%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -d Account-Zepto-qa/qa/zepto_wallet`
</details>
Plan: 0 to add, 1 to change, 0 to destroy.

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by ayukha-zepto** [comment]
atlantis apply

**Comment by ayukha-zepto** [comment]
Ran Apply for 4 projects:

1. dir: `Account-Zepto-production/zepto_rewards` workspace: `default`
1. dir: `Account-Zepto-production/zepto_wallet` workspace: `default`
1. dir: `Account-Zepto-qa/qa/zepto_rewards` workspace: `default`
1. dir: `Account-Zepto-qa/qa/zepto_wallet` workspace: `default`

### 1. dir: `Account-Zepto-production/zepto_rewards` workspace: `default`
**Apply Failed**: Pull request must be approved by at least one person other than the author before running apply.

---
### 2. dir: `Account-Zepto-production/zepto_wallet` workspace: `default`
**Apply Failed**: Pull request must be approved by at least one person other than the author before running apply.

---
### 3. dir: `Account-Zepto-qa/qa/zepto_rewards` workspace: `default`
**Apply Failed**: Pull request must be approved by at least one person other than the author before running apply.

---
### 4. dir: `Account-Zepto-qa/qa/zepto_wallet` workspace: `default`
**Apply Failed**: Pull request must be approved by at least one person other than the author before running apply.

---

**Review by shrutijodevops — APPROVED** [review]
approved

**Comment by ayukha-zepto** [comment]
atlantis apply

**Comment by ayukha-zepto** [comment]
Ran Apply for 4 projects:

1. dir: `Account-Zepto-production/zepto_rewards` workspace: `default`
1. dir: `Account-Zepto-production/zepto_wallet` workspace: `default`
1. dir: `Account-Zepto-qa/qa/zepto_rewards` workspace: `default`
1. dir: `Account-Zepto-qa/qa/zepto_wallet` workspace: `default`

### 1. dir: `Account-Zepto-production/zepto_rewards` workspace: `default`
<details><summary>Show Output</summary>

```diff
aws_instance.zepto_rewards: Destroying... [id=i-0c443956a11601c58]
aws_instance.zepto_rewards_prod: Creating...
aws_instance.zepto_rewards: Still destroying... [id=i-0c443956a11601c58, 10s elapsed]
aws_instance.zepto_rewards_prod: Still creating... [10s elapsed]
aws_instance.zepto_rewards_prod: Creation complete after 12s [id=i-0286c4a47d902508a]
aws_instance.zepto_rewards: Still destroying... [id=i-0c443956a11601c58, 20s elapsed]
aws_instance.zepto_rewards: Still destroying... [id=i-0c443956a11601c58, 30s elapsed]
aws_instance.zepto_rewards: Still destroying... [id=i-0c443956a11601c58, 40s elapsed]
aws_instance.zepto_rewards: Still destroying... [id=i-0c443956a11601c58, 50s elapsed]
aws_instance.zepto_rewards: Destruction complete after 1m0s

Apply complete! Resources: 1 added, 0 changed, 1 destroyed.
```

</details>

---
### 2. dir: `Account-Zepto-production/zepto_wallet` workspace: `default`
```diff
aws_instance.Zepto_wallet: Destroying... [id=i-0504eb4a77cdb8db7]
aws_instance.Zepto_wallet_prod: Creating...
aws_instance.Zepto_wallet: Still destroying... [id=i-0504eb4a77cdb8db7, 10s elapsed]
aws_instance.Zepto_wallet_prod: Still creating... [10s elapsed]
aws_instance.Zepto_wallet_prod: Creation complete after 12s [id=i-02f40b21a75eb1976]
aws_instance.Zepto_wallet: Still destroying... [id=i-0504eb4a77cdb8db7, 20s elapsed]
aws_instance.Zepto_wallet: Destruction complete after 30s

Apply complete! Resources: 1 added, 0 changed, 1 destroyed.
```

---
### 3. dir: `Account-Zepto-qa/qa/zepto_rewards` workspace: `default`
**Apply Error**
```
running "/usr/local/bin/terraform1.4.6 apply -input=false \"/atlantis-data/repos/ayukha-zepto/Atlantis_Test/4/default/Account-Zepto-qa/qa/zepto_rewards/default.tfplan\"" in "/atlantis-data/repos/ayukha-zepto/Atlantis_Test/4/default/Account-Zepto-qa/qa/zepto_rewards": exit status 1
╷
│ Error: Saved plan is stale
│ 
│ The given plan file can no longer be applied because the state was changed
│ by another operation after the plan was created.
╵

```

---
### 4. dir: `Account-Zepto-qa/qa/zepto_wallet` workspace: `default`
**Apply Error**
```
running "/usr/local/bin/terraform1.4.6 apply -input=false \"/atlantis-data/repos/ayukha-zepto/Atlantis_Test/4/default/Account-Zepto-qa/qa/zepto_wallet/default.tfplan\"" in "/atlantis-data/repos/ayukha-zepto/Atlantis_Test/4/default/Account-Zepto-qa/qa/zepto_wallet": exit status 1
╷
│ Error: Saved plan is stale
│ 
│ The given plan file can no longer be applied because the state was changed
│ by another operation after the plan was created.
╵

```

---

**Comment by ayukha-zepto** [comment]
Locks and plans deleted for the projects and workspaces modified in this pull request:

- dir: `Account-Zepto-production/zepto_rewards` workspace: `default`
- dir: `Account-Zepto-production/zepto_wallet` workspace: `default`
- dir: `Account-Zepto-qa/qa/zepto_rewards` workspace: `default`
- dir: `Account-Zepto-qa/qa/zepto_wallet` workspace: `default`

**Pull request merged**
